export const metadata = {
  title: "Portfolio - Showcase of Projects",
  description: "Generated by create next app",
};

export default function About({ children }: { children: React.ReactNode }) {
  return <div className="">{children}</div>;
}
